#########################################################################
# ⭐⭐⭐  Set parameters carefully for satisfied performance!   ⭐⭐⭐ #
#########################################################################

mass        : 1.2 # kg 
gra         : 9.81 
ctrl_freq_max   : 100.0
use_bodyrate_ctrl: false
max_manual_vel: 1.0
max_angle: 30  # Attitude angle limit in degree. A negative value means no limit.
low_voltage: 13.2 # 4S battery

rc_reverse: # *
    roll: false
    pitch: false
    yaw: false
    throttle: false

auto_takeoff_land:
    enable: true
    enable_auto_arm: true
    no_RC: true
    takeoff_height: 1.0 # m
    takeoff_land_speed: 0.3 # m/s

thrust_model: # The model that maps thrust signal u(0~1) to real thrust force F(Unit:N)
    print_value: false 
    accurate_thrust_model: false  
    K1: 0.7583 # Needs precise calibration!
    K2: 1.6942 # Needs precise calibration!
    K3: 0.6786 # Needs precise calibration!
    hover_percentage: 0.30  

# SE3 Controller Gains
se3_controller:
    position_gains:
        kp_xy: 3.0      # horizontal position P gain
        kp_z: 15.0      # vertical position P gain
        
    velocity_gains:
        kv_xy: 2.0      # horizontal velocity P gain
        kv_z: 8.0       # vertical velocity P gain
        
    acceleration_gains:
        ka_xy: 1.0      # horizontal acceleration feedforward gain
        ka_z: 1.0       # vertical acceleration feedforward gain
        
    attitude_gains:
        kq_roll_pitch: 3.0   # roll/pitch attitude gain
        kq_yaw: 2.0          # yaw attitude gain
        
    attitude_rate_gains:
        kw_roll_pitch: 4.0   # roll/pitch rate gain
        kw_yaw: 4.0          # yaw rate gain
        
    integral_gains:
        ki_xy_world: 0.1     # world frame xy integral gain
        ki_xy_body: 0.1      # body frame xy integral gain
        ki_xy_world_lim: 10.0  # world frame xy integral limit
        ki_xy_body_lim: 10.0   # body frame xy integral limit
        
    mass_estimator:
        km: 1.0          # mass estimator gain
        km_lim: 3.0      # mass estimator limit [kg]
        
    constraints:
        tilt_angle_failsafe: 90.0  # [deg] failsafe tilt angle
        throttle_saturation: 0.9   # throttle saturation limit

msg_timeout:
    odom: 0.5
    rc:   0.5
    cmd:  0.5
    imu:  0.5
    bat:  0.5